services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn crud.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crud.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-gmail-app-password
      - fromDatabase:
          name: crud-db
          property: connectionString

  - type: web
    name: react-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build

databases:
  - name: crud-db
    plan: free
